language: groovy
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- wget -q https://gist.githubusercontent.com/djtfmartin/220d74fc793695ff95c5/raw/ed23ec5ea18c099dd4edf3370de1104813c11c2c/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh

- ala_travis_grails_setup_env

script:
- ala_travis_grails_build

env:
  global:
  - secure: M5RdnCEQHqRvytpOCDWhxSw6oOZLGYODdhHkmCy+5z8zKLWYchwcCSOdGgmEGU9oeEndg1erPKXuvRlpjWHq2VnaFh2EVg8rA82LoB4PkOzqwmCevLdTL6R+ePO/ZHoZo2PoLSbGHV38RkhFI+GTa9s+4/JZjNrm45a2eJx+GaU=
  - secure: G9qlN6dGDN4RF+137R3lOAXQnTY0uhbt69TyPnaFUFlhUo/ngonaHkULCtDWujcmqkwoWh8QqybmO2XpG78cicFmzcrruQmDVqj2mi7VikDp722rLbSkop44E3xPVNAS1NAb9nyKyZlPMxmxncAA5O6TA//UPtsjIn1HrENJJ/o=
